[platformio]
description = myMota32 ESP32 replacement firmware
default_envs = mymota32-esp32-c3-4m, mymota32-esp32-d0wd-v3-4m, mymota32-esp32-u4wdh-d-4m, mymota32-esp32-u4wdh-s-4m
src_dir = src
build_cache_dir = .cache

[common]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.f_cpu = 160000000L
board_build.partitions = partitions.csv
build_unflags =
  -Wall
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DNDEBUG
  -DMYMOTA32_VERSION=\"0.3.0\"
  -Wl,-Map,firmware.map
  -include src/nimble_no_security.h
lib_ignore =
  ArduinoOTA
  WebServerSecure
lib_deps =
  h2zero/NimBLE-Arduino @ 2.5.0

[env:mymota32-esp32-c3-4m]
platform = ${common.platform}
framework = ${common.framework}
board = esp32-c3-devkitm-1
board_build.f_cpu = ${common.board_build.f_cpu}
board_build.f_flash = 80000000L
board_build.flash_mode = dio
board_build.partitions = ${common.board_build.partitions}
build_unflags = ${common.build_unflags}
build_flags =
  ${common.build_flags}
  -DMYMOTA32_TARGET=\"esp32-c3-4m\"
monitor_speed = ${common.monitor_speed}
upload_speed = ${common.upload_speed}
lib_ignore = ${common.lib_ignore}
lib_deps = ${common.lib_deps}

[env:mymota32-esp32-d0wd-v3-4m]
platform = ${common.platform}
framework = ${common.framework}
board = esp32dev
board_build.f_cpu = ${common.board_build.f_cpu}
board_build.f_flash = 40000000L
board_build.flash_mode = dio
board_build.partitions = ${common.board_build.partitions}
build_unflags = ${common.build_unflags}
build_flags =
  ${common.build_flags}
  -DMYMOTA32_TARGET=\"esp32-d0wd-v3-4m\"
monitor_speed = ${common.monitor_speed}
upload_speed = ${common.upload_speed}
lib_ignore = ${common.lib_ignore}
lib_deps = ${common.lib_deps}

[env:mymota32-esp32-u4wdh-d-4m]
platform = ${common.platform}
framework = ${common.framework}
board = esp32dev
board_build.f_cpu = ${common.board_build.f_cpu}
board_build.f_flash = 40000000L
board_build.flash_mode = dio
board_build.partitions = ${common.board_build.partitions}
build_unflags = ${common.build_unflags}
build_flags =
  ${common.build_flags}
  -DMYMOTA32_TARGET=\"esp32-u4wdh-d-4m\"
  -DMYMOTA32_ESP32_U4WDH=1
monitor_speed = ${common.monitor_speed}
upload_speed = ${common.upload_speed}
lib_ignore = ${common.lib_ignore}
lib_deps = ${common.lib_deps}

[env:mymota32-esp32-u4wdh-s-4m]
platform = ${common.platform}
framework = ${common.framework}
board = esp32-solo1
board_espidf.custom_sdkconfig =
board_build.f_cpu = ${common.board_build.f_cpu}
board_build.f_flash = 40000000L
board_build.flash_mode = dio
board_build.partitions = ${common.board_build.partitions}
build_unflags = ${common.build_unflags}
build_flags =
  ${common.build_flags}
  -DMYMOTA32_TARGET=\"esp32-u4wdh-s-4m\"
  -DMYMOTA32_ESP32_U4WDH=1
  -DFRAMEWORK_ARDUINO_SOLO1
monitor_speed = ${common.monitor_speed}
upload_speed = ${common.upload_speed}
lib_ignore = ${common.lib_ignore}
lib_deps = ${common.lib_deps}
